SELECT 
    ORDER_ITEMS.ORDER_ID,
    ITEMS.NAME,
    ITEMS.PRICE,
    ORDER_ITEMS.QUANTITY
FROM
    ITEMS
        JOIN
    ORDER_ITEMS ON ITEMS.ITEM_ID = ORDER_ITEMS.ITEM_ID
        JOIN
    ORDERS ON ORDER_ITEMS.ORDER_ID = ORDERS.ORDER_ID
        JOIN
    STORES ON ORDERS.STORE_ID = STORES.STORE_ID
WHERE
    STORES.CITY = 'New York'
ORDER BY ORDER_ID;