WITH result AS (
	SELECT STORES.NAME AS NAME, COUNT(ORDERS.STORE_ID) AS QUANTITY
    FROM ORDERS
    JOIN STORES
    USING (STORE_ID)
    GROUP BY NAME
	)
SELECT NAME, QUANTITY,
	CASE QUANTITY
		WHEN QUANTITY > 3 THEN 'High'
		WHEN QUANTITY <= 1 THEN 'Low'
        ELSE 'Medium'
	END SALES_FIGURE
FROM result
ORDER BY QUANTITY DESC;